---
- name: Copy nginx configuration file and restart service if changed
  hosts: localhost
  become: true
  tasks:
    - name:  Copy nginx.conf to the correct location
      ansible.builtin.copy:
        src: nginx.conf # Direction of the file you will copy
        dest: /etc/nginx/nginx.conf # target destination
        mode: '0644' # roles
        remote_src: yes # will copy to remote locations from root src file in my case
      notify: Restart nginx
  handlers:
    - name: Restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

