---
- name: Running firewall
  hosts: localhost
  tasks:
    - name: start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: true
      when: (ansible_facts["distribution"] == "Fedora" and ansible_facts["distribution_major_version"] | int > 7) or (ansible_facts["distribution"] == "CentOS" and ansible_facts["distribution_major_version"] | int  > 8)
